import { Url } from "next/dist/shared/lib/router/router"

namespace NodeJS {
    interface ProcessEnv {
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:string
STRIPE_SECRET_KEY:string
 STRIPE_WEBHOOK_SECRET:string
 FETCHANALYTICSPAGEVIEW:url
 FETCHCOMMANDSEARCH:url
 FETCHPRODUCTADD:url
 FETCHANALYTICSPAGEVIEW:url
 FETCHPRODUCTIMGUPLOADDEV:url
FETCHPRODUCTIMGUPLOADPROD:url
 FETCHANALYTICSEVENT:url
 FETCHLOGINDEV:url
 FETCHLOGINPROD:url
 ADDUSERDEV:url
 ADDUSERPROD:url
 USERCHANGESDEV:url
 USERCHANGESPROD:url
 FINDUSERDEV:url
 FINDUSERPROD:string
 USERCONNDEV:url
 USERCONNPROD:url
 FETCHBLOGIMGDEV:url
 FETCHBLOGIMGPROD:url
    }}