
import './globals.css'
import { Inter } from 'next/font/google'
import DesktopMenu from '@/components/Menu/MenuDesktop/menu'
import Text from '@/components/TexteSwitch/text'
import Footer from '@/components/footer/footer'
import { ProductContextProvider } from './Context/productStore'
import {CartContextProvider} from './Context/cartContext'
import { CommandeContextProvider } from './Context/commandeContext'
import UserContextProvider from './Context/UserAccountContext'
import { AnalyticsContextProvider } from './Context/analyticsContext'
import Menusticky from '@/components/Menu/MenuDesktop/Menu sticky/menuSticky'
import { BlogContextProvider} from './Context/blogContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
        
        <ProductContextProvider>
        <CartContextProvider>
          <AnalyticsContextProvider>
          <UserContextProvider>
          <BlogContextProvider>
            <CommandeContextProvider>
            <DesktopMenu Text={Text}/>
            <Menusticky/>
        {children}
        <Footer Text={Text}/>
        </CommandeContextProvider>
        </BlogContextProvider>
        </UserContextProvider>
        </AnalyticsContextProvider>
        </CartContextProvider>
        </ProductContextProvider>
        
        
        </body>
    </html>
  )
}
