import './globals.css'
import { Inter } from 'next/font/google'
import DesktopMenu from '@/components/Menu/MenuDesktop/menu'
import Text from '@/components/TexteSwitch/text'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DesktopMenu Text={Text}/>
        {children}
        <Footer Text={Text}/>
        </body>
    </html>
  )
}
